version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
    depends_on:
      - backend
    expose:
      - 3000


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    env_file:  
      - ./backend/.env 
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=exercise_db
    depends_on:
      - mongodb
    expose:
      - 5000


  mongodb:
    image: mongo:4.4
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
